<!DOCTYPE html>
<html>
	<head>
		<title>ELA</title>
		<meta charset="utf-8">
		<link rel="stylesheet" type="text/css" href="css/hoja.css">
		<script type="text/javascript" src="js/jquery.js"></script>
		<script type="text/javascript" src="js/codigo.js"></script>
	</head>

	<body>
		<header>
			<a href="index.php"><h1>Tienda online</h1></a>
			<h2>Subtitulo de la tienda</h2>
		</header>
			<div class="carro">
				Carrito
			</div>